class CantMatchTypeError(ValueError): ...

class PyMagic:
    def mime_type(self) -> str: ...
    def extension(self) -> str: ...
    def is_image(self) -> bool: ...
    def is_app(self) -> bool: ...
    def is_archive(self) -> bool: ...
    def is_audio(self) -> bool: ...
    def is_book(self) -> bool: ...
    def is_document(self) -> bool: ...
    def is_font(self) -> bool: ...
    def is_video(self) -> bool: ...
    def is_text(self) -> bool: ...

def from_bytes(buf: bytes) -> PyMagic: ...
def from_path(path: str) -> PyMagic: ...
